#!/bin/sh

if [ "$ALTNAME" = "" ]; then
  echo "ENV:ALTNAME missing (subjectAltName)"
  exit 1
fi

if [ "$CN" = "" ]; then
  echo "ENV:CN missing (common name)"
  exit 1
fi

if [ ! -d /certs ]; then
  echo "you need to specify a volume for certificate files mapped to /certs"
  exit 1
fi

openssl req -x509 -sha256 -nodes -newkey rsa:4096 -keyout /certs/privkey.pem -out /certs/cert.pem -days 365 -subj '/CN=$CN' -config /etc/ssl/openssl.cnf -extensions SAN
